server:
    port: 8080
javax:
    sql:
        DataSource:
            airportDataSource:
                dataSourceClassName: oracle.jdbc.driver.OracleDriver
                dataSource:
                    url: jdbc:oracle:thin:@localhost:1521/DEV_APP_CONN
                    user: APPUSER
                    password: appuserpwd