server:
    port: 8081
javax:
    sql:
        DataSource:
           employeeDataSource:
                dataSourceClassName: oracle.jdbc.pool.OracleDataSource
                dataSource:
                    url: jdbc:oracle:thin:@localhost:1521/xe
                    user: appuser
                    password: appuserpwd