show user;
desc greeting;

--USER_MASTER table
create TABLE USER_MASTER(
    SSO_ID varchar(10),
    USER_ID INT,
    USER_TYPE varchar(10),
    USER_ROLE varchar(10)
);

--USER_ROLES table
create TABLE USER_ROLES(
    ROLE_ID INT,
    ROLE_NAME varchar(10)
);

--USER_ROLES INSERT
INSERT INTO USER_ROLES
    VALUES(100,'GM');
INSERT INTO USER_ROLES
    VALUES(101,'RM');
INSERT INTO USER_ROLES
    VALUES(102,'MGR');
INSERT INTO USER_ROLES
    VALUES(103,'FO');
INSERT INTO USER_ROLES
    VALUES(104,'RE');    
    
--USER_MASTER INSERT
INSERT INTO USER_MASTER
    VALUES('SSO2001', 5001 ,'A','GM');